### ISSUE TITLE
TPC-H support

### ISSUE THREAD

**Issue by penberg** [tursodatabase/limbo#36]
This is an umbrella issue for supporting the TPC-H benchmark.

### Tasks

- [x] https://github.com/penberg/limbo/issues/37
- [x] https://github.com/penberg/limbo/issues/80
- [x] https://github.com/penberg/limbo/issues/31
- [x] https://github.com/penberg/limbo/issues/32
- [x] https://github.com/penberg/limbo/issues/33
- [x] https://github.com/penberg/limbo/issues/35
- [x] https://github.com/penberg/limbo/issues/397
- [x] https://github.com/penberg/limbo/issues/398
- [x] https://github.com/penberg/limbo/issues/399
- [ ] https://github.com/penberg/limbo/issues/34
- [ ] https://github.com/penberg/limbo/issues/4

### Tools

* https://github.com/tarantool/tpch
* [Data set generator](https://github.com/lovasoa/TPCH-sqlite)
* [Query generator](https://github.com/KowalskiThomas/LLVMSQLite/tree/master/llvmsqlite_util/benchmarking)

### References

[TPC-H specification](https://www.tpc.org/TPC_Documents_Current_Versions/pdf/TPC-H_v3.0.1.pdf)

**Comment by LtdJorge** [comment]
I think this should be reopened

**Comment by thisismiller** [comment]
I see `CAST` support was marked as fixed, but the specific usage of CAST() in Q5 still isn't supported, so here's #2756 to add to your list.

**Comment by penberg** [comment]
@jussisaurio I moved full TPC-H support to 0.3 milestone. There are some TPC-H related bugs we want to fix, but full support is not out of scope for 0.2

**Comment by roboturso** [comment]
This issue was triaged by @roboturso and determined to be out of scope: This is an umbrella tracking issue for TPC-H benchmark support rather than a report of a runtime failure, so there is nothing to reproduce.
